services:
  configserver:
    build:
      context: ./configserver
      dockerfile: Dockerfile
    ports:
      - "8071:8071"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  account:
    build:
      context: ./account
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071

  cards:
    build:
      context: ./cards
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071

  loans:
    build:
      context: ./loans
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
